### ISSUE TITLE
Unable to import servermanager module in EXE, but works in ps1

### ISSUE THREAD

**Issue by j-sabrsula** [nickrod518/PowerShell-Scripts#1]
Exe unable to find servermanager module but ps1 file equivalent is able to. 

To reproduce:

Run this code in a ps1 script:
import-module servermanager
get-module
Read-Host

Run 'Create-EXEFrom' on this ps1 script.
Copy both ps1 file and exe to Windows Server 2012.
See attachment for results when both are executed. The exe throws a terminating error of 'FileNotFound' for some reason.

![image](https://cloud.githubusercontent.com/assets/11077362/13953683/1ff72644-f00b-11e5-8de7-2984461bd680.png)

**Comment by nickrod518** [comment]
Thank you for posting this. Do you experience the same issues with other modules, or just servermanager? Off the top of my head I'm thinking this may have something to do with the user's path that the exe is run as.

**Comment by j-sabrsula** [comment]
Edit: I figured this out- you can either change the 64 bit powershell modules to include the 32 bit powershell modules manually in your script along with the other code, or you can change the 'create-exefrom' code iexpress section to path C:\WINDOWS\System32\iexpress, which creates a 32 bit executable instead of a 64 bit executable. Ultimately, running the 32 bit powershell version fixes this, but there's more powershell exe's in Windows Server, and if you create a 64 bit executable, it uses it via the 64 bit powershell directory. Also, depending on your memory requirements, you may want to use the 64 bit powershell version anyway, in which case I imagine the first option I offered would be sufficient. 

(original response) Just servermanager, as far as what I use, though there may be others. There's multiple powershell exes in Windows server 2012, each with their own module directories. After testing, it appears the powershell path that mimics the behavior i'm getting the servermanager import failure is located in C:\Windows\SysWOW64\WindowsPowerShell\v1.0 (64 bit powershell), whereas the one located in C:\Windows\System32\WindowsPowerShell\v1.0 (32 bit powershell) works fine as expected. 

![image](https://cloud.githubusercontent.com/assets/11077362/14078497/dc417aca-f4bb-11e5-84ca-69a5062bdad1.png)

![image](https://cloud.githubusercontent.com/assets/11077362/14078528/2ce18056-f4bc-11e5-859e-1cdb18b009b5.png)

**Comment by nickrod518** [comment]
If I added a parameter such as -64Bit that would run the 64-bit iexpress, would this resolve the issue?

**Comment by j-sabrsula** [comment]
Yes, I think leaving it to the user to specify what version of executable they want would be ideal, maybe leave the 32 bit version as default, for compatibility reasons. It's a bit tricky as there's considerations in making both types available. Maybe append something to the generated exe file name itself like filename (32-bit)/(64-bit), for clarity.

**Comment by nickrod518** [comment]
32 bit being default is exactly what I was thinking, and the user would use the -64Bit switch to change that. That's a great idea to append something to the file name for clarity.

March 29 2016 9:38 AM, "j-sabrsula"  wrote:
    Yes, I think leaving it to the user to specify what version of executable they want would be ideal, maybe leave the 32 bit version as default, for compatibility reasons. It's a bit tricky as there's considerations in making both types available. Maybe append something to the generated exe file name itself like filename (javascript:false)/(64-bit), for clarity.

```
—
```

**Comment by nickrod518** [comment]
I've pushed the latest update. There is an x64 switch now (params can't start with numbers or else I'd use 64Bit). Using this switch will create the exe using 64-bit iexpress and also apped " (x64)" to the target exe's name. I'm closing this issue, please reopen if you find this change doesn't suit your needs, and thank you very much for the suggestion!
