### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by mongrol** [nickrod518/PowerShell-Scripts#3]
Is it possible to have an icon embedded in?

**Comment by nickrod518** [comment]
iexpress does not support custom icons, so it would have to be some other way after you've created your EXE. If you find a method that works I can add it to the script.

**Comment by nickrod518** [comment]
FYI, I'm moving this project to its own repo - https://github.com/nickrod518/Create-EXEFromPS1

**Comment by nickrod518** [comment]
I'm closing this issue here and opening a new one in the new project. Thank you for submitting.
