### ISSUE TITLE
Send-CatFactMessage.ps1

### ISSUE THREAD

**Issue by HurtzDonut** [nickrod518/PowerShell-Scripts#6]
IWR returns: 

`Invoke-WebRequest : Python 2.5 is no longer available. Please refer to https://goo.gl/aESk5L for more information.
At line:45 char:35`
`+ ... tFrom-Json (Invoke-WebRequest -Uri 'http://catfacts-api.appspot.com/a ...`
`+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
    `+ CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException`
    `+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by nickrod518** [comment]
It appears that Api doesn't work anymore. I've updated the function to use 'https://catfact.ninja/fact' instead.
